name 'opticpow-deluge'
version '1.0.1'
dependency 'rodjek/logrotate', '1.x'
author 'Wayne Ingram'
license 'MIT'
project_page 'https://github.com/opticpow/puppet-deluge'
source 'https://github.com/opticpow/puppet-deluge'
summary 'Puppet Module for the Deluge Bittorrent Client'
description ''
